// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDITeTX2zyPyja6Nub_gSyzhmDizTKQQJY',
    appId: '1:864965303140:web:b936b2ec76880eb8957871',
    messagingSenderId: '864965303140',
    projectId: 'fir-integration-d00bf',
    authDomain: 'fir-integration-d00bf.firebaseapp.com',
    storageBucket: 'fir-integration-d00bf.appspot.com',
    measurementId: 'G-T8F7QZV7VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByeHYPwbaVuWK87YV3fo4xvM-XHWwj9Qs',
    appId: '1:864965303140:android:d9b8ba957f899b0a957871',
    messagingSenderId: '864965303140',
    projectId: 'fir-integration-d00bf',
    storageBucket: 'fir-integration-d00bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjh9TvDdofGp_2ifjrMew3LviuS3sD3iM',
    appId: '1:864965303140:ios:7d4ed827aa274b3c957871',
    messagingSenderId: '864965303140',
    projectId: 'fir-integration-d00bf',
    storageBucket: 'fir-integration-d00bf.appspot.com',
    iosClientId: '864965303140-0u53s6ro07rdsi1irmnn9sqidlp5stv6.apps.googleusercontent.com',
    iosBundleId: 'com.app.firebaseIntegration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjh9TvDdofGp_2ifjrMew3LviuS3sD3iM',
    appId: '1:864965303140:ios:7d4ed827aa274b3c957871',
    messagingSenderId: '864965303140',
    projectId: 'fir-integration-d00bf',
    storageBucket: 'fir-integration-d00bf.appspot.com',
    iosClientId: '864965303140-0u53s6ro07rdsi1irmnn9sqidlp5stv6.apps.googleusercontent.com',
    iosBundleId: 'com.app.firebaseIntegration',
  );
}
